name: Run API Test with Newman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run Newman with HTML report
        run: |
          newman run postman_login_collection.json \
            -e postman_env.json \
            -r cli,html \
            --reporter-html-export newman-report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html
